const PatentList = () => {
    return (
        <div>
            <div>Patent List!!</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
            <div>Patent List</div>
        </div>
    );
};

export default PatentList;
