version: "3.8"
services:
 patent-ideas-core:
  image: patent-ideas-core
  build:
   context: .
   target: build
  volumes:
   - ./:/app
   - /app/node_modules
  ports:
   - 3000:3000
  command: pnpm dev
