
### 
GET http://localhost:3000/ 
### 
GET http://localhost:3000/admin/idea 

### 
POST http://localhost:3000/admin/idea/create HTTP/1.1
content-type: application/json

{
    "title": "Who the fuck is?",
    "subtitle": "Nisi occaecat adipisicing.",
    "details": "Aliquip elit excepteur laborum minim dolore fugiat mollit cillum sit pariatur nisi occaecat adipisicing."
}
